theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: 项目经理

# 对你自己的简洁描述
description: 这人很懒，什么描述都没写

# 你的美照地址
logo: /assets/images/wei.jpg

# 你的名字
name: 郭  巍(Wei Guo)

# 你的联系方式
phone: 188888888888

# 你的邮箱
email: wei@unkown.com

# 你目前的住址
address: 陕西西安

# 你毕业院校
school: 电子科技大学

# 你的专业
profession: 自动化

# 你的学位
degree: 硕士

# 你获得过的证书或奖励
credential: 无
